### PR TITLE
Fix mistake

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ba0f3** [comment]
i fixed but not commit yet, thank you so much!

**Comment by konqoro** [comment]
line 49. Jsmn.nim raises `JsmnNotEnoughTokensException` exception. I changed it because of that but then it failed in line 26! Fun times.

**Comment by konqoro** [comment]
Wow you are fast!

**Comment by konqoro** [comment]
Ok then so plz don't merge yet. I will wait till you commit your changes and add the rest of the tests.

**Pull request merged**
